// This file will be auto-generated by ml_pipeline/export_to_c.py
// A dummy placeholder is provided to compile.

#ifndef TRANSIENT_MODEL_DATA_H
#define TRANSIENT_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

const unsigned int g_model_data_len = 0;
const unsigned char g_model_data[] __attribute__((aligned(4))) = {
    0x00
};

#ifdef __cplusplus
}
#endif

#endif // TRANSIENT_MODEL_DATA_H
